// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  cloudfoundryConcepts: [
    {
      type: 'category',
      label: 'Cloud Foundry concepts',
      link: {
        type: 'doc',
        id: 'docs-cloudfoundry-concepts/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'docs-cloudfoundry-concepts/cloudfoundry-concepts'},
      ],
    },
    {
      type: 'category',
      label: 'Cloud Foundry Command Line Interface (cf CLI)',
      link: {
        type: 'doc',
        id: 'docs-cf-cli/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'docs-cf-cli/docs'},
      ],
    },
    'docs-cloudfoundry-concepts/contribute',
  ],
  devGuideSidebar: [
    {
      type: 'category',
      label: 'App developer guide',
      link: {
        type: 'doc',
        id: 'docs-dev-guide/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'docs-dev-guide/docs'}
      ],
    },
    {
      type: 'category',
      label: 'Cloud Foundry Buildpacks',
      link: {
        type: 'doc',
        id: 'docs-buildpacks/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'docs-buildpacks/docs'}
      ],
    },
  ],
  // buildpacksSidebar: [{type: 'autogenerated', dirName: 'docs-buildpacks'},{type: 'ref', id: 'docs-dev-guide/docs/index'},],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
