import MDXComponents from '@theme-original/MDXComponents'
import {CFDevLink, AppDomain, SSL, APIEndpoint, RecommendedBy, GlobalAuditorRole, CFNetworking, AppSvcLinks, ComplianceLinks, IpsecNote, ConsoleLinks, ManageIsoSegLink, AdminRole, AdminReadOnlyRole, BillingManagerRoleNote, BillingManagerRole, OrAppsMan, PlatformName, AppSecGroupsDefault, ContainerNetworkLink, AppRuntimeAbbr, AppRuntimeFirst, ConceptsSfVsFullHeader, SmallFootprintComparison, ConceptsProductModelHeader, ConceptsProductModelImage, OpsManager, CompanyName, AsgNote, AppSecGroupsLink} from '@site/src/components/Constants'
import ConditionalContent from '@site/src/components/ConditionalContent'
import CustomComponents from '@site/src/components/ComponentProvider'

export default {
  ...MDXComponents,
  AppRuntimeAbbr,
  ConditionalContent,
  AppRuntimeFirst,
  ConceptsSfVsFullHeader,
  SmallFootprintComparison,
  ConceptsProductModelHeader,
  ConceptsProductModelImage,
  OpsManager,
  CompanyName,
  AsgNote,
  AppSecGroupsLink,
  ContainerNetworkLink,
  AppSecGroupsDefault,
  PlatformName,
  OrAppsMan,
  BillingManagerRoleNote,
  BillingManagerRole,
  AdminRole,
  AdminReadOnlyRole,
  ManageIsoSegLink,
  ConsoleLinks,
  IpsecNote,
  ComplianceLinks,
  AppSvcLinks,
  CFNetworking,
  GlobalAuditorRole,
  RecommendedBy,
  APIEndpoint,
  SSL,
  AppDomain,
  CFDevLink,
  ...CustomComponents,
};
